name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "cb765547b8d14714898af5c4fab87848" },
  { binding = "SHARE", id = "79c2e5cde33545b1a1186c651513afb2" }
]